language: java

jdk:
  - oraclejdk8
  - openjdk7

install:
  - mvn test -DskipTests=true -B -V
  - jdk_switcher use oraclejdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
  - jdk_switcher use $TRAVIS_JDK_VERSION
